; pause.g
; called when a print from SD card is paused
;
M42 P0 S250   ;leds test
; generated by RepRapFirmware Configuration Tool v3.3.12 on Sat Aug 20 2022 15:16:14 GMT+0200 (hora de verano de Europa central)
M83            ; relative extruder moves
G1 E-0.5 F3600  ; retract 0.5mm of filament
G91            ; relative positioning
G1 Z20 F360     ; lift Z by 20mm
G90            ; absolute positioning
G1 X0 Y0 F6000 ; go to X=0 Y=0

