; resume.g
; called before a print from SD card is resumed
;
M42 P0 S200    ;leds printing
; generated by RepRapFirmware Configuration Tool v3.3.12 on Sat Aug 20 2022 15:16:14 GMT+0200 (hora de verano de Europa central)
G1 R1 X0 Y0 Z20 F6000 ; go to 5mm above position of the last print move
G1 R1 X0 Y0 Z0       ; go back to the last print move
M83                  ; relative extruder moves
G1 E0.5 F3600         ; extrude 0.5mm of filament

